### ISSUE TITLE
BallerinaPackgeService components API is provided Invalid document identifiers for toml files

### ISSUE THREAD

**Issue by malinthar** [wso2/ballerina-plugin-vscode#111]
**Description:**
When I did a text edit in the Ballerina.toml file in a  package, [the components API in BallerinaPcakageServiceImpl](https://github.com/ballerina-platform/ballerina-lang/blob/e446dfca6274849d85333f99ae7e01066ead2ab9/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/BallerinaPackageServiceImpl.java#L90-L109) throws an exception as shown in the stack trace below. 

```
[Error - 1:45:04 pm] Operation 'ballerinaPackage/components' failed! {, error: 'provided path is not a regular file: /home/malintha/Documents/wso2/experimental/testing/project1/project1'}
io.ballerina.projects.ProjectException: provided path is not a regular file: /home/malintha/Documents/wso2/experimental/testing/project1/project1
	at io.ballerina.projects.util.ProjectPaths.packageRoot(ProjectPaths.java:53)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectKindAndProjectRoot(BallerinaWorkspaceManager.java:825)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectRoot(BallerinaWorkspaceManager.java:817)
	at com.google.common.cache.LocalCache.lambda$computeIfAbsent$0(LocalCache.java:4204)
	at com.google.common.cache.LocalCache$LoadingValueReference.compute(LocalCache.java:3567)
	at com.google.common.cache.LocalCache$Segment.compute(LocalCache.java:2243)
	at com.google.common.cache.LocalCache.compute(LocalCache.java:4197)
	at com.google.common.cache.LocalCache.computeIfAbsent(LocalCache.java:4204)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectRoot(BallerinaWorkspaceManager.java:126)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.project(BallerinaWorkspaceManager.java:137)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.lambda$components$2(BallerinaPackageServiceImpl.java:98)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.lambda$components$3(BallerinaPackageServiceImpl.java:97)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageServiceImpl.lambda$components$4(BallerinaPackageServiceImpl.java:96)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

The issue seems to be the invalid document identifier provided by the LS Client. In the above case the document identifier passed is root path of the package(does not contain  Ballerina.toml file name).

The case is the same for other toml variations as well.

**Steps to reproduce:**
Follow above steps

**Comment by mohanvive** [comment]
@Prabhashi FYA
