### ISSUE TITLE
`ballerinaPackage/metadata` API throws project exception

### ISSUE THREAD

**Issue by nadeeshaan** [wso2/ballerina-plugin-vscode#153]
**Description:**
Refer the following capture where the `ballerinaPackage/metadata` extension API throws project exception due to the invalid URI

https://user-images.githubusercontent.com/1329674/148730108-084637fb-a003-41cb-bc7b-f123a820ce72.mp4

```
[Error - 12:47:20 PM] Operation 'ballerinaPackage/metadata' failed! {uri: '/', error: 'provided directory does not belong to a Ballerina package: /'}
io.ballerina.projects.ProjectException: provided directory does not belong to a Ballerina package: /
	at io.ballerina.projects.util.ProjectPaths.packageRoot(ProjectPaths.java:64)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectKindAndProjectRoot(BallerinaWorkspaceManager.java:999)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectRoot(BallerinaWorkspaceManager.java:991)
	at com.google.common.cache.LocalCache.lambda$computeIfAbsent$0(LocalCache.java:4204)
	at com.google.common.cache.LocalCache$LoadingValueReference.compute(LocalCache.java:3567)
	at com.google.common.cache.LocalCache$Segment.compute(LocalCache.java:2243)
	at com.google.common.cache.LocalCache.compute(LocalCache.java:4197)
	at com.google.common.cache.LocalCache.computeIfAbsent(LocalCache.java:4204)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectRoot(BallerinaWorkspaceManager.java:133)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.project(BallerinaWorkspaceManager.java:150)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageService.lambda$metadata$0(BallerinaPackageService.java:73)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Affected Versions:**
v3.0.0-preview-m6 at least

**Comment by prabushi** [comment]
This was fixed with https://github.com/wso2-enterprise/ballerina-plugin-vscode/pull/267. The fix is available in https://github.com/wso2/ballerina-plugin-vscode/releases/tag/v3.0.0-preview-m7

**Comment by prabushi** [comment]
This error is still reproducible in 3.0.0-preview-m9.
