### ISSUE TITLE
Package metadata request results in exception

### ISSUE THREAD

**Issue by malinthar** [wso2/ballerina-plugin-vscode#165]
**Description:**
The following exception was thrown as I opened the daigram view. 

```

[Error - 2:02:29 pm] Operation 'ballerinaPackage/metadata' failed! {uri: '/', error: 'provided directory does not belong to a Ballerina package: /'}
io.ballerina.projects.ProjectException: provided directory does not belong to a Ballerina package: /
	at io.ballerina.projects.util.ProjectPaths.packageRoot(ProjectPaths.java:64)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectKindAndProjectRoot(BallerinaWorkspaceManager.java:999)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.computeProjectRoot(BallerinaWorkspaceManager.java:991)
	at com.google.common.cache.LocalCache.lambda$computeIfAbsent$0(LocalCache.java:4204)
	at com.google.common.cache.LocalCache$LoadingValueReference.compute(LocalCache.java:3567)
	at com.google.common.cache.LocalCache$Segment.compute(LocalCache.java:2243)
	at com.google.common.cache.LocalCache.compute(LocalCache.java:4197)
	at com.google.common.cache.LocalCache.computeIfAbsent(LocalCache.java:4204)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.projectRoot(BallerinaWorkspaceManager.java:133)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.project(BallerinaWorkspaceManager.java:150)
	at org.ballerinalang.langserver.extensions.ballerina.packages.BallerinaPackageService.lambda$metadata$0(BallerinaPackageService.java:73)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Steps to reproduce:**
Try opening the diagram view in a multi module project.

**Affected Versions:**
SL-GA-rc1
plugin-version: v3.0.0-preview-m7

**Comment by mohanvive** [comment]
Reproducible for simple bal file as well. But only for the `Show Diagram` right-side corner button.

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/ballerina-plugin-vscode/issues/153
