### ISSUE TITLE
Connector action form fails with Ballerina Update 1

### ISSUE THREAD

**Issue by prabushi** [wso2/ballerina-plugin-vscode#193]
**Description:**
The connector action form isn't loaded once the client is selected in the connector form with the 2201.1.0-rc4 Ballerina release. This happens only if we separately create an action. "Continue to Invoke API" flow in the connector form seems to work fine.  
And, the same flow seems to work with the previous Ballerina versions (2201.0.3, etc.)

The following error is thrown for the `ballerinaConnector/connector` LS call.
```
[Trace - 9:32:27 PM] Sending request 'ballerinaConnector/connector - (22)'.
Params: {
    "name": "Client",
    "moduleName": "http",
    "orgName": "ballerina",
    "packageName": "http",
    "version": "2.3.0",
    "targetFile": "/Users/prabushi/Desktop/hello/main.bal"
}


[Trace - 9:32:28 PM] Received notification 'telemetry/event'.
Params: {
    "message": "Operation 'ballerinaConnector/connector' failed!",
    "errorMessage": "java.lang.IllegalStateException: closed",
    "errorStackTrace": "Error: java.lang.IllegalStateException: closed\n\tat okio.RealBufferedSource.select(RealBufferedSource.kt:83)\n\tat okhttp3.internal.Util.bomAwareCharset(Util.java:467)\n\tat okhttp3.ResponseBody.string(ResponseBody.java:181)\n\tat org.ballerinalang.central.client.CentralAPIClient.handleResponseErrors(CentralAPIClient.java:882)\n\tat org.ballerinalang.central.client.CentralAPIClient.getConnector(CentralAPIClient.java:841)\n\tat org.ballerinalang.langserver.extensions.ballerina.connector.BallerinaConnectorService.getConnectorFromCentral(BallerinaConnectorService.java:212)",
    "type": "ErrorTelemetryEvent",
    "component": "component.langserver.ballerinaConnector_record",
    "version": "2201.1.0-rc1.14"
}


[Trace - 9:32:28 PM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "Operation 'ballerinaConnector/connector' failed! {, error: 'closed'}\njava.lang.IllegalStateException: closed\n\tat okio.RealBufferedSource.select(RealBufferedSource.kt:83)\n\tat okhttp3.internal.Util.bomAwareCharset(Util.java:467)\n\tat okhttp3.ResponseBody.string(ResponseBody.java:181)\n\tat org.ballerinalang.central.client.CentralAPIClient.handleResponseErrors(CentralAPIClient.java:882)\n\tat org.ballerinalang.central.client.CentralAPIClient.getConnector(CentralAPIClient.java:841)\n\tat org.ballerinalang.langserver.extensions.ballerina.connector.BallerinaConnectorService.getConnectorFromCentral(BallerinaConnectorService.java:212)\n\tat org.ballerinalang.langserver.extensions.ballerina.connector.BallerinaConnectorService.lambda$connector$1(BallerinaConnectorService.java:184)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)\n"
}


[Error - 9:32:28 PM] Operation 'ballerinaConnector/connector' failed! {, error: 'closed'}
java.lang.IllegalStateException: closed
	at okio.RealBufferedSource.select(RealBufferedSource.kt:83)
	at okhttp3.internal.Util.bomAwareCharset(Util.java:467)
	at okhttp3.ResponseBody.string(ResponseBody.java:181)
	at org.ballerinalang.central.client.CentralAPIClient.handleResponseErrors(CentralAPIClient.java:882)
	at org.ballerinalang.central.client.CentralAPIClient.getConnector(CentralAPIClient.java:841)
	at org.ballerinalang.langserver.extensions.ballerina.connector.BallerinaConnectorService.getConnectorFromCentral(BallerinaConnectorService.java:212)
	at org.ballerinalang.langserver.extensions.ballerina.connector.BallerinaConnectorService.lambda$connector$1(BallerinaConnectorService.java:184)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

[Trace - 9:32:28 PM] Received response 'ballerinaConnector/connector - (22)' in 1362ms.
Result: {}

```

Although the `ballerinaConnector/connector` request sent for "2.3.0" HTTP connector version, `ballerinaConnector/connectors` response seems to have cached the "2.2.1" version at the start.

<img width="992" alt="Screenshot 2022-05-25 at 21 43 37" src="https://user-images.githubusercontent.com/5234623/170309396-9616a41e-bc55-4ee7-a523-8d77cda3015c.png">

**Steps to reproduce:**
- Add an HTTP connector
- Add an action using the created connector

**Affected Versions:**
With the latest low-code changes https://github.com/wso2/ballerina-plugin-vscode/releases/tag/v20220525-1 and the 2201.1.0-rc4 Ballerina release.

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kanushka** [comment]
## RCA

when adding action, we are using  [`/connectors/{orgNamePath}/{packageNamePath}/{versionPath}/{moduleNamePath}/{connectorNamePath}`](https://github.com/wso2-enterprise/ballerina-registry/blob/main/src/registry_package_api/resources/openapi/ballerina-registry-openapi-spec.yaml#L625) API in the Ballerina central. For that request we collect data form the source syntax tree. Here, with the 2201.1.0-rc4 Ballerina release, the source syntax tree provide below data.
```
"name": "Client",
"moduleName": "http",
"orgName": "ballerina",
"packageName": "http",
"version": "2.3.0",
```

But Ballerina central doesn't provide connector information for the above package version.
https://api.dev-central.ballerina.io/2.0/registry/connectors/ballerina/http/2.3.0/http/Client

![image](https://user-images.githubusercontent.com/24244523/170413136-1df7b9ed-8a14-4e0c-805d-e322c756ec30.png)
