### ISSUE TITLE
Fix test failures on Windows

### ISSUE THREAD

**Issue by prabushi** [wso2/ballerina-plugin-vscode#44]
<a href="https://github.com/prabushi"><img src="https://avatars.githubusercontent.com/u/5234623?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [prabushi](https://github.com/prabushi)**
_Tuesday Mar 30, 2021 at 12:33 GMT_
_Originally opened as https://github.com/ballerina-platform/plugin-vscode/issues/338_

----

**Description:**
Following errors are noticed from debug adapter test client and LS client tests.
```
rejected promise not handled within 1 second: TypeError: Cannot read property 'write' of undefined
stack trace: TypeError: Cannot read property 'write' of undefined
    at DebugClient.doSend (D:\a\plugin-vscode\plugin-vscode\node_modules\vscode-debugadapter-testsupport\src\protocolClient.ts:97:21)
    at D:\a\plugin-vscode\plugin-vscode\node_modules\vscode-debugadapter-testsupport\src\protocolClient.ts:72:9
    at new Promise (<anonymous>)
    at DebugClient.send (D:\a\plugin-vscode\plugin-vscode\node_modules\vscode-debugadapter-testsupport\src\protocolClient.ts:71:10)
    at DebugClient.terminateRequest (D:\a\plugin-vscode\plugin-vscode\node_modules\vscode-debugadapter-testsupport\src\debugClient.ts:175:15)
    at Context.<anonymous> (D:\a\plugin-vscode\plugin-vscode\test\debugger\debugger.test.ts:75:12)
    at callFn (d:\a\plugin-vscode\plugin-vscode\node_modules\mocha\lib\runnable.js:372:21)
    at Hook.Runnable.run (d:\a\plugin-vscode\plugin-vscode\node_modules\mocha\lib\runnable.js:364:7)
    at next (d:\a\plugin-vscode\plugin-vscode\node_modules\mocha\lib\runner.js:317:10)
    at Immediate.<anonymous> (d:\a\plugin-vscode\plugin-vscode\node_modules\mocha\lib\runner.js:347:5)
    at processImmediate (internal/timers.js:456:21)
```

```
Language Server Tests
       "before all" hook:
     Uncaught Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
<a href="https://github.com/prabushi"><img src="https://avatars.githubusercontent.com/u/5234623?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [prabushi](https://github.com/prabushi)**
_Wednesday Mar 31, 2021 at 02:10 GMT_

----

Enabled LS tests with https://github.com/ballerina-platform/plugin-vscode/pull/339
